# Generated by Django 4.1 on 2022-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forms', models.CharField(choices=[('cow_meat', 'Cow Meat'), ('fish', 'Fish'), ('turkey', 'Turkey'), ('chicken', 'Chicken')], max_length=20, verbose_name='options:')),
                ('buying', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
